"""empty message

Revision ID: 0ef83e97042d
Revises: 59e872b494ba
Create Date: 2025-08-03 21:29:51.225295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef83e97042d'
down_revision = '59e872b494ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('privileges', sa.Integer(), nullable=False),
    sa.Column('color_class', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('privileges')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privileges_groups')
    # ### end Alembic commands ###
