"""Add creator and is_approved columns

Revision ID: 1cad5c5e90c4
Revises: f395fd361ef4
Create Date: 2025-08-23 10:37:05.104144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cad5c5e90c4'
down_revision = 'f395fd361ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
