"""empty message

Revision ID: 22750caf5291
Revises: d1de047991d4
Create Date: 2025-08-07 00:32:16.703240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22750caf5291'
down_revision = 'd1de047991d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_deleted',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_deleted')
    # ### end Alembic commands ###
