"""update clan and clan members

Revision ID: 274764cf6f6e
Revises: d696ecd9644a
Create Date: 2025-08-17 20:48:32.435323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274764cf6f6e'
down_revision = 'd696ecd9644a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clanm_clan_id'))
        batch_op.create_index('ix_clan_members_clan_id', ['clan_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_clanm_clan_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_clanm_user_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_clan_members_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_clan_members_clan_id_clans', 'clans', ['clan_id'], ['id'])
        batch_op.drop_column('privileges')

    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key('fk_clans_leader_id_users', 'users', ['leader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clans_leader_id_users', type_='foreignkey')
        batch_op.drop_column('leader_id')

    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privileges', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_clan_members_clan_id_clans', type_='foreignkey')
        batch_op.drop_constraint('fk_clan_members_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_clanm_user_id'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_clanm_clan_id'), 'clans', ['clan_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_clan_members_clan_id')
        batch_op.create_index(batch_op.f('ix_clanm_clan_id'), ['clan_id'], unique=False)

    # ### end Alembic commands ###
