"""Add table PrivilegesGroups

Revision ID: 2947d7d7c1d7
Revises: 9afd1fb3814f
Create Date: 2025-08-11 21:06:03.111935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2947d7d7c1d7'
down_revision = '9afd1fb3814f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('privileges', sa.Integer(), nullable=False),
    sa.Column('color_class', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privileges_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privileges_groups_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('privileges_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privileges_groups_name'))

    op.drop_table('privileges_groups')
    # ### end Alembic commands ###
