"""change column int2str

Revision ID: 31fd83e29584
Revises: 1b6ca91250d6
Create Date: 2025-08-24 08:51:34.353475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31fd83e29584'
down_revision = '1b6ca91250d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_name', sa.String(length=255), nullable=False))
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('job_name')

    # ### end Alembic commands ###
