"""Add avatar field

Revision ID: 4018d9a61296
Revises: 22c202753064
Create Date: 2025-08-19 22:50:30.047119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '4018d9a61296'
down_revision = '22c202753064'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    conn.execute(sa.text("UPDATE users SET avatar_file = :avatar_file WHERE id = 999"), {
        "avatar_file": "dfad6bb89246fffbeeba3056eaae640b.jpg"
    })


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_file')

    # ### end Alembic commands ###
