"""add table users

Revision ID: 4ebfd33cf507
Revises: 
Create Date: 2025-08-27 09:11:34.041418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebfd33cf507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=32), nullable=False),
        sa.Column('username_aka', sa.String(length=32), nullable=True),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('userpage', sa.Text(), nullable=True),
        sa.Column('privileges', sa.BigInteger(), server_default='3', nullable=False),
        sa.Column('avatar_file', sa.String(length=255), nullable=True),
        sa.Column('country', sa.CHAR(length=2), server_default='XX', nullable=False),
        sa.Column('sponsor_expire', sa.DateTime(timezone=True), nullable=True),
        sa.Column('register_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_privileges'), ['privileges'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
    op.execute("ALTER TABLE users AUTO_INCREMENT = 1000")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_privileges'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
