"""Fix foreign key from clan

Revision ID: 59f3acc1346a
Revises: c2d7fd088567
Create Date: 2025-08-13 12:14:06.661963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f3acc1346a'
down_revision = 'c2d7fd088567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.alter_column('leader_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_clan_leader_id', 'users', ['leader_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clan_leader_id', type_='foreignkey')
        batch_op.alter_column('leader_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
