"""add column background_image

Revision ID: 65e5a1ac20e6
Revises: 4ebfd33cf507
Create Date: 2025-08-28 18:38:34.116191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e5a1ac20e6'
down_revision = '4ebfd33cf507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('background_file')

    # ### end Alembic commands ###
