"""update field price

Revision ID: 704592ad1029
Revises: 8f077fccb4fe
Create Date: 2025-08-22 20:11:57.205149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '704592ad1029'
down_revision = '8f077fccb4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=36, scale=18),
               type_=sa.Numeric(precision=36, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=36, scale=2),
               type_=mysql.DECIMAL(precision=36, scale=18),
               existing_nullable=False)

    # ### end Alembic commands ###
