"""Update field in Users

Revision ID: 7b191c0d1e1c
Revises: 2947d7d7c1d7
Create Date: 2025-08-12 12:08:57.924796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b191c0d1e1c'
down_revision = '2947d7d7c1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_expire', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('support_expire')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_expire', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sponsor_expire')

    # ### end Alembic commands ###
