"""add table privileges groups

Revision ID: 7b4f09e73fd8
Revises: 65e5a1ac20e6
Create Date: 2025-09-04 11:37:50.363146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4f09e73fd8'
down_revision = '65e5a1ac20e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges_groups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('privileges', sa.BigInteger(), nullable=False),
        sa.Column('color', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        mysql_charset='utf8',
        mysql_engine='InnoDB'
    )
    # op.execute("ALTER TABLE users AUTO_INCREMENT = 1000")
    op.execute("""
    INSERT INTO privileges_groups (id, name, privileges, color) VALUES
    (1, 'Забанен', 0, 'dark'),
    (2, 'Ограничен', 2, 'warning'),
    (3, 'Игрок', 3, 'primary'),
    (4, 'Спонсор', 7, 'warning'),
    (5, 'Полный доступ', 15, 'info');
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privileges_groups')
    # ### end Alembic commands ###
