"""add table user balance

Revision ID: 8f077fccb4fe
Revises: 960001affb2c
Create Date: 2025-08-22 00:55:43.951243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f077fccb4fe'
down_revision = '960001affb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'crypto_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_balances')
    # ### end Alembic commands ###
