"""add table cryptocurrency

Revision ID: 960001affb2c
Revises: a6113df5c76f
Create Date: 2025-08-22 00:47:40.461691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960001affb2c'
down_revision = 'a6113df5c76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('logo_file', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###
