"""logo to icon field

Revision ID: 99ddc82be9d2
Revises: 704592ad1029
Create Date: 2025-08-22 21:02:45.904261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99ddc82be9d2'
down_revision = '704592ad1029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_file', sa.String(length=255), nullable=True))
        batch_op.drop_column('logo_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_file', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('icon_file')

    # ### end Alembic commands ###
