"""add table clan_members

Revision ID: b8ffb69c2a40
Revises: 59f3acc1346a
Create Date: 2025-08-13 23:26:06.072734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ffb69c2a40'
down_revision = '59f3acc1346a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('clan_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], name='fk_clanm_clan_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_clanm_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.create_index('ix_clanm_clan_id', ['clan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.drop_index('ix_clanm_clan_id')

    op.drop_table('clan_members')
    # ### end Alembic commands ###
