"""add column privileges for Clan Members

Revision ID: cba81fa6068a
Revises: b8ffb69c2a40
Create Date: 2025-08-14 21:48:58.512568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba81fa6068a'
down_revision = 'b8ffb69c2a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privileges', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.drop_column('privileges')

    # ### end Alembic commands ###
