"""empty message

Revision ID: d1de047991d4
Revises: 37c4dd89c009
Create Date: 2025-08-06 10:25:01.291716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1de047991d4'
down_revision = '37c4dd89c009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_logs_users_uid', 'users', ['uid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logs_users_uid', type_='foreignkey')

    # ### end Alembic commands ###
