"""Deleted lider_id from Clan

Revision ID: d696ecd9644a
Revises: cba81fa6068a
Create Date: 2025-08-14 21:50:56.513412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd696ecd9644a'
down_revision = 'cba81fa6068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clan_leader_id'), type_='foreignkey')
        batch_op.drop_column('leader_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_id', sa.BIGINT(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_clan_leader_id'), 'users', ['leader_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
