"""add crypto price history

Revision ID: f395fd361ef4
Revises: 99ddc82be9d2
Create Date: 2025-08-22 23:50:40.661502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f395fd361ef4'
down_revision = '99ddc82be9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_price_history')
    # ### end Alembic commands ###
